### PR TITLE
UserdataTypes and Line Info Fix

### LINKED ISSUE #34: attempt to perform arithmetic (add) on nil and number
I got the following error when using the bytecode below:
```
fiu.lua:459: attempt to perform arithmetic (add) on nil and number
stacktrace:
fiu.lua:459 function readProto
fiu.lua:506 function luau_deserialize
fiu.lua:533 function luau_load
fiu.lua:1281
```
[bytecode.tar.gz](https://github.com/rce-incorporated/Fiu/files/15237383/bytecode.tar.gz)

### PR DESCRIPTION
**Pull request by NovazUwU**
Closes #34

### CODE REVIEW

File: Source.lua [hunk 1]
```diff
@@ -40,6 +40,8 @@ local ttisstring = function(v) return type(v) == "string" end
 local ttisboolean = function(v) return type(v) == "boolean" end
 local ttisfunction = function(v) return type(v) == "function" end
 
+local int_cast = function(n) return n % (2 ^ 32) end
```
Comment (SnorlaxAssist) [inline Source.lua:43]: Remove this (check next comment)

File: Source.lua [hunk 2]
```diff
@@ -472,14 +474,14 @@ local function luau_deserialize(bytecode, luau_settings)
 			local lastline = 0
 			for j = 1, intervals do
 				lastline += readWord()
-				abslineinfo[j] = lastline
+				abslineinfo[j] = int_cast(lastline)
```
Comment (SnorlaxAssist) [inline Source.lua:477]: change to 
```lua
abslineinfo[j] = lastline % (2 ^ 32)
```

**Review by SnorlaxAssist — CHANGES_REQUESTED** [review]
